### Request to Your API Endpoint
POST http://127.0.0.1:8000/api/relation/retrieve-tree
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xMjcuMC4wLjFcL3RoaW5rYS1hcGlcL3B1YmxpY1wvYXBpXC9sb2dpbiIsImlhdCI6MTczODUwMzg4MSwiZXhwIjoxNzM4NTkwMjgxLCJuYmYiOjE3Mzg1MDM4ODEsImp0aSI6ImlObnpVMENFNmFkNUZFV1giLCJzdWIiOjUsInBydiI6IjM4ZTRiY2U4MTVjZjI4YzJhM2FmNTQxNDljY2JlMTMzMmEzZTZjNmMiLCJjdXN0b20iOnsiY29tcGFueV9pZCI6MSwicm9sZXMiOnsiMTAxIjp0cnVlfSwidXNlciI6eyJpZCI6NCwidXNlcl9pZCI6NSwiZmlyc3RfbmFtZSI6Imp1YW4iLCJtaWRkbGVfbmFtZSI6IiIsImxhc3RfbmFtZSI6ImNydXoiLCJiaXJ0aGRhdGUiOm51bGwsImNyZWF0ZWRfYXQiOiIyMDIwLTExLTEyVDE1OjU3OjI0LjAwMDAwMFoiLCJ1cGRhdGVkX2F0IjoiMjAyMC0xMS0xMlQxNTo1NzoyNC4wMDAwMDBaIiwiZGVsZXRlZF9hdCI6bnVsbCwiZnVsbF9uYW1lIjoiY3J1eiBqdWFuIiwicHJvZmlsZV9waG90b19maWxlX25hbWUiOm51bGx9fX0.sWm7vsjxEIG3OmuCEA6Kz6esd_Mepn73jGsQ3jkfRnI
Content-Type: application/json
Accept: application/json

{
  "relation_id": 971
}
